In [ ]:
1) Program to implement k-NN classification using any standard dataset available in the public
domain and find the accuracy of the algorithm.

In [11]:
import numpy as np
import matplotlib.pyplot  as plt
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
x,y = load_iris(return_X_y = True)
pd.DataFrame(x)


0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .20)
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [14]:
y_pred

array([0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 0, 1, 2, 1, 2, 2, 0])

In [15]:
y_test

array([0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 2, 1, 1, 2, 0])

In [16]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 6,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 10]])

In [17]:
ac = accuracy_score(y_test,y_pred)
ac

0.9333333333333333

In [18]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.86      0.92        14
           2       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.95      0.94        30
weighted avg       0.94      0.93      0.93        30

