In [ ]:
6) Program to create a 5x5 zero matrix with elements on the main diagonal.

In [5]:

import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
